# Site settings
title: Easily Fascinated
description: >
  Hi! I’m David Keck. This is Easily Fascinated. It’s my website. 
  It’s about endless curiosity and fascination for life.
  It’s one of my ways of following Mary Oliver’s wonderful instructions for living a life. 
  "Instructions for living a life. Pay attention. Be astonished. Tell about it."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidskeck.github.io/" # the base hostname & protocol for your site

author:
  fullname: David Keck
  github: davidskeck
  disqus: davidskeck

# Syntax highlighting
highlightstyle: 'dracula'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, dracula, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
